# Generated by Django 6.0.2 on 2026-03-02 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_rename_source_transaction_payment_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('bank_details', models.JSONField(default=dict, help_text='Store IFSC, Acc No, etc.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='expense_groups', to='social.contact')),
            ],
        ),
        migrations.CreateModel(
            name='BillSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equal'), ('CUSTOM', 'Custom Amount')], max_length=10)),
                ('split_details', models.JSONField()),
                ('is_settled', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.group')),
            ],
        ),
    ]
