# Generated by Django 6.0.2 on 2026-03-02 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_non_numeric_app_name(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE finance_transaction SET payment_app_name = NULL "
            "WHERE payment_app_name IS NOT NULL AND payment_app_name !~ '^[0-9]+$'"
        )
        cursor.execute(
            "UPDATE finance_transaction SET payment_source_name = NULL "
            "WHERE payment_source_name IS NOT NULL AND payment_source_name !~ '^[0-9]+$'"
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_notes_transaction_payment_app_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_non_numeric_app_name, noop),
        migrations.RenameField(
            model_name='transaction',
            old_name='source',
            new_name='payment_source_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_app',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.paymentapp'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_app_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_by_app_name', to='finance.paymentapp'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method_name',
            field=models.CharField(choices=[('UPI', 'UPI Payment'), ('CASH', 'Cash'), ('ATM', 'ATM Withdrawal'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('WALLET', 'Wallet'), ('NET_BANKING', 'Net Banking'), ('CHECK', 'Check'), ('TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_source_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_by_source_name', to='finance.paymentsource'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('UPI', 'UPI Payment'), ('CASH', 'Cash'), ('ATM', 'ATM Withdrawal'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('WALLET', 'Wallet'), ('NET_BANKING', 'Net Banking'), ('CHECK', 'Check'), ('TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, help_text='Display name', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentmethod'),
        ),
    ]
