# Generated by Django 6.0.2 on 2026-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_source_transaction_payment_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_app_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
