# Generated by Django 6.0.2 on 2026-03-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_payment_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_app_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_by_app_name', to='finance.paymentapp'),
        ),
    ]
