# Generated by Django 6.0.2 on 2026-03-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_transaction_payment_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_app_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_source_name',
        ),
    ]
