# Generated by Django 6.0.2 on 2026-03-03 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_upi_source_types_credit_debit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['key'], 'verbose_name': 'Payment source type', 'verbose_name_plural': 'Payment source types'},
        ),
        migrations.RemoveConstraint(
            model_name='paymentappsource',
            name='finance_paymentappsource_unique_app_method_source',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Null = built-in method; set = user's custom method.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='key',
            field=models.CharField(help_text='e.g. BANK, CREDIT_CARD', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='label',
            field=models.CharField(help_text='Display name e.g. Bank Account', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='paymentappsource',
            unique_together={('payment_app', 'payment_method', 'payment_source')},
        ),
    ]
